.TH "P_threads_N_threads Directory Reference" 3 "Tue Jun 7 2022" "cough_cough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
P_threads_N_threads Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBP_threads_N_threads\&.c\fP"
.br
.ti -1c
.RI "file \fBP_threads_N_threads\&.h\fP"
.br
.in -1c
