.TH "consumer_data" 3 "Tue Jun 7 2022" "cough_cough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
consumer_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <P_threads_N_threads\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int * \fBfds\fP"
.br
.ti -1c
.RI "uint32_t \fBfirst_ts\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int* fds"

.SS "uint32_t first_ts"


.SH "Author"
.PP 
Generated automatically by Doxygen for cough_cough from the source code\&.
