.TH "consumer_hash_data" 3 "Tue Jun 7 2022" "cough_cough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
consumer_hash_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map_reduce\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDATASET\fP * \fBdata\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBfd_out\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBDATASET\fP* data"

.SS "int fd_out"

.SS "int id"


.SH "Author"
.PP 
Generated automatically by Doxygen for cough_cough from the source code\&.
