.TH "from_N_threads_to_file/from_N_threads_to_file.c" 3 "Tue Jun 7 2022" "cough_cough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
from_N_threads_to_file/from_N_threads_to_file.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <pthread\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'from_N_threads_to_file\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for cough_cough from the source code\&.
