.TH "from_socket_to_file/from_socket_to_file.c" 3 "Tue Jun 7 2022" "cough_cough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
from_socket_to_file/from_socket_to_file.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'from_socket_to_file\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfrom_parent_socket_to_file\fP (int fd_out, int N_processes, \fBDATASET\fP data)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void from_parent_socket_to_file (int fd_out, int N_processes, \fBDATASET\fP data)"
socket writes to file 
.PP
\fBParameters:\fP
.RS 4
\fIfd_out\fP file descriptor 
.br
\fIN_processes\fP number of N processes 
.br
\fIdata\fP data 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cough_cough from the source code\&.
