.TH "from_N_processes_to_parent_to_file/from_N_processes_to_parent_to_file.h" 3 "Tue Jun 7 2022" "cough_cough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
from_N_processes_to_parent_to_file/from_N_processes_to_parent_to_file.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <occupation/occupation\&.h>\fP
.br
\fC#include 'io/io\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfrom_N_processes_to_parent_to_file\fP (int fd_out, int N_processes, \fBDATASET\fP data)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void from_N_processes_to_parent_to_file (int fd_out, int N_processes, \fBDATASET\fP data)"
N processes write back to parent process 
.PP
\fBParameters:\fP
.RS 4
\fIfd_out\fP file descriptor 
.br
\fIN_processes\fP number of child processes 
.br
\fIdata\fP data 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cough_cough from the source code\&.
