.TH "line" 3 "Tue Jun 7 2022" "cough_cough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
line \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parser\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBareas_timestamps\fP [\fBNUM_AREAS\fP]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t areas_timestamps[\fBNUM_AREAS\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for cough_cough from the source code\&.
