.TH "main.c" 3 "Tue Jun 7 2022" "cough_cough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include 'from_N_processes_to_file/from_N_processes_to_file\&.h'\fP
.br
\fC#include 'from_N_processes_to_parent_to_file/from_N_processes_to_parent_to_file\&.h'\fP
.br
\fC#include 'from_N_processes_to_parent_to_M_processes/from_N_processes_to_parent_to_M_processes\&.h'\fP
.br
\fC#include 'from_socket_to_file/from_socket_to_file\&.h'\fP
.br
\fC#include 'from_N_threads_to_file/from_N_threads_to_file\&.h'\fP
.br
\fC#include 'P_threads_N_threads/P_threads_N_threads\&.h'\fP
.br
\fC#include 'map_reduce/map_reduce\&.h'\fP
.br
\fC#include 'parser/parser\&.h'\fP
.br
\fC#include 'occupation/occupation\&.h'\fP
.br
\fC#include 'io/io\&.h'\fP
.br
\fC#include 'socket/socket\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for cough_cough from the source code\&.
