.TH "node" 3 "Tue Jun 7 2022" "cough_cough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <queue\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBformatted_data\fP [128]"
.br
.ti -1c
.RI "struct \fBnode\fP * \fB_next\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBnode\fP* _next"

.SS "char formatted_data[128]"


.SH "Author"
.PP 
Generated automatically by Doxygen for cough_cough from the source code\&.
