.TH "libs/occupation/occupation.c" 3 "Tue Jun 7 2022" "cough_cough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libs/occupation/occupation.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'occupation\&.h'\fP
.br
\fC#include '\&.\&./io/io\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBoccupation\fP (const \fBDATASET\fP data, int id, int fd_write, pid_t pid)"
.br
.ti -1c
.RI "void \fBwrite_to_fd\fP (int id, uint32_t timestamp, const char *room, int \fBoccupation\fP, int fd_write, pid_t pid)"
.br
.ti -1c
.RI "void \fBcheck_if_sorted\fP (\fBDATASET\fP *data)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void check_if_sorted (\fBDATASET\fP * data)"
checks if data is sorted 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP data to be used 
.RE
.PP

.SS "void occupation (\fBDATASET\fP data, int id, int fd_write, pid_t pid)"
calculates occupation 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP data to be used 
.br
\fIid\fP line number 
.br
\fIfd_write\fP file descriptor to write to 
.br
\fIpid\fP pid of process 
.RE
.PP

.SS "void write_to_fd (int id, uint32_t timestamp, const char * room, int occupation, int fd, pid_t pid)"
writes data to file descriptor 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP line number 
.br
\fItimestamp\fP timestamp 
.br
\fIroom\fP room which calculation was made 
.br
\fIoccupation\fP number of people in the room 
.br
\fIfd\fP file descriptor 
.br
\fIpid\fP process id 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cough_cough from the source code\&.
