.TH "libs/parser/parser.c" 3 "Tue Jun 7 2022" "cough_cough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libs/parser/parser.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'parser\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBload_data\fP (const char *filename, \fBDATASET\fP *data)"
.br
.ti -1c
.RI "int \fBfile_sz\fP (const char *filename)"
.br
.ti -1c
.RI "void \fBparse_buffer\fP (char *buffer, \fBDATASET\fP *data)"
.br
.ti -1c
.RI "int \fBget_line_size\fP (const char *buffer)"
.br
.ti -1c
.RI "void \fBfree_double_buffer\fP (char **arr, int size)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int file_sz (const char * filename)"
calculates file size: numbers of characters until 'EOF' is reached 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP file opened 
.RE
.PP
\fBReturns:\fP
.RS 4
size of file 
.RE
.PP

.SS "void free_double_buffer (char ** arr, int size)"
deallocates supporting data 
.PP
\fBParameters:\fP
.RS 4
\fIarr\fP dt to be freed 
.br
\fIsize\fP size of dt 
.RE
.PP

.SS "int get_line_size (const char * buffer)"
calculates line size: number of characters until '
.br
' is reached 
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP buffer to read 
.RE
.PP
\fBReturns:\fP
.RS 4
size of line 
.RE
.PP

.SS "void load_data (const char * filename, \fBDATASET\fP * data)"
loads data from filename into memory 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP file to open 
.br
\fIdata\fP dataset for data to be stored 
.RE
.PP

.SS "void parse_buffer (char * buffer, \fBDATASET\fP * data)"
parses retrieved data from file into the dataset 
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP 
.br
\fIdata\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cough_cough from the source code\&.
