.TH "libs/parser/parser.h" 3 "Tue Jun 7 2022" "cough_cough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libs/parser/parser.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBline\fP"
.br
.ti -1c
.RI "struct \fBdataset\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNUM_AREAS\fP   5"
.br
.ti -1c
.RI "#define \fBNOT_VALID_TIMESTAMP\fP   9999"
.br
.ti -1c
.RI "#define \fBONE_YEAR_UNIX_TS\fP   31556926"
.br
.ti -1c
.RI "#define \fBONE_DAY_UNIX_TS\fP   86400"
.br
.ti -1c
.RI "#define \fBONE_WEEK_UNIX_TS\fP   604800"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBline\fP \fBLINE\fP"
.br
.ti -1c
.RI "typedef struct \fBdataset\fP \fBDATASET\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBload_data\fP (const char *filename, \fBDATASET\fP *data)"
.br
.ti -1c
.RI "int \fBfile_sz\fP (const char *filename)"
.br
.ti -1c
.RI "void \fBparse_buffer\fP (char *buffer, \fBDATASET\fP *data)"
.br
.ti -1c
.RI "int \fBget_line_size\fP (const char *buffer)"
.br
.ti -1c
.RI "void \fBfree_double_buffer\fP (char **arr, int size)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NOT_VALID_TIMESTAMP   9999"

.SS "#define NUM_AREAS   5"

.SS "#define ONE_DAY_UNIX_TS   86400"

.SS "#define ONE_WEEK_UNIX_TS   604800"

.SS "#define ONE_YEAR_UNIX_TS   31556926"

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBdataset\fP \fBDATASET\fP"

.SS "typedef struct \fBline\fP \fBLINE\fP"

.SH "Function Documentation"
.PP 
.SS "int file_sz (const char * filename)"
calculates file size: numbers of characters until 'EOF' is reached 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP file opened 
.RE
.PP
\fBReturns:\fP
.RS 4
size of file 
.RE
.PP

.SS "void free_double_buffer (char ** arr, int size)"
deallocates supporting data 
.PP
\fBParameters:\fP
.RS 4
\fIarr\fP dt to be freed 
.br
\fIsize\fP size of dt 
.RE
.PP

.SS "int get_line_size (const char * buffer)"
calculates line size: number of characters until '
.br
' is reached 
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP buffer to read 
.RE
.PP
\fBReturns:\fP
.RS 4
size of line 
.RE
.PP

.SS "void load_data (const char * filename, \fBDATASET\fP * data)"
loads data from filename into memory 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP file to open 
.br
\fIdata\fP dataset for data to be stored 
.RE
.PP

.SS "void parse_buffer (char * buffer, \fBDATASET\fP * data)"
parses retrieved data from file into the dataset 
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP 
.br
\fIdata\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cough_cough from the source code\&.
