.TH "queue" 3 "Tue Jun 7 2022" "cough_cough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
queue \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <queue\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBNODE\fP * \fBfirst\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBNODE\fP* first"

.SS "int size"


.SH "Author"
.PP 
Generated automatically by Doxygen for cough_cough from the source code\&.
