.TH "shared_dt_hash" 3 "Tue Jun 7 2022" "cough_cough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shared_dt_hash \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map_reduce\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBadmissions_line\fP [\fBMAX_DT_SZ\fP]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t admissions_line[\fBMAX_DT_SZ\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for cough_cough from the source code\&.
