.TH "shared_dt" 3 "Tue Jun 7 2022" "cough_cough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shared_dt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <P_threads_N_threads\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBbuffer\fP [\fBMAX_DT_SZ\fP][\fBARR_SZ\fP]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char buffer[\fBMAX_DT_SZ\fP][\fBARR_SZ\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for cough_cough from the source code\&.
