.TH "libs/socket/socket.c" 3 "Tue Jun 7 2022" "cough_cough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libs/socket/socket.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'socket\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcreate_socket_client\fP (char *socket_path)"
.br
.ti -1c
.RI "int \fBcreate_socket_server\fP (char *socket_path)"
.br
.ti -1c
.RI "void \fBfrom_socket_to_file\fP (int listen_fd, int fd_out)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int create_socket_client (char * socket_path)"
creates a socket client 
.PP
\fBParameters:\fP
.RS 4
\fIsocket_path\fP socket path 
.RE
.PP
\fBReturns:\fP
.RS 4
descriptor referencing the socket created 
.RE
.PP

.SS "int create_socket_server (char * socket_path)"
creates a socket server 
.PP
\fBParameters:\fP
.RS 4
\fIsocket_path\fP socket path 
.RE
.PP
\fBReturns:\fP
.RS 4
file descriptor referencing the socket created 
.RE
.PP

.SS "void from_socket_to_file (int listenfd, int fd_out)"
writes the content received by the socket to file 
.PP
\fBParameters:\fP
.RS 4
\fIlistenfd\fP file descriptor referencing the socket 
.br
\fIfd_out\fP file to write to 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cough_cough from the source code\&.
