.TH "thread_data" 3 "Tue Jun 7 2022" "cough_cough" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thread_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <from_N_threads_to_file\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDATASET\fP * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBstarting_point\fP"
.br
.ti -1c
.RI "size_t \fBjump_count\fP"
.br
.ti -1c
.RI "int \fBfd_out\fP"
.br
.ti -1c
.RI "int \fBn_consumers\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBDATASET\fP* data"

.SS "int fd_out"

.SS "size_t jump_count"

.SS "int n_consumers"

.SS "size_t starting_point"


.SH "Author"
.PP 
Generated automatically by Doxygen for cough_cough from the source code\&.
